apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: classroomregistry.azurecr.io/git-classroom:6.3.2
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 6379
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: classroomregistry.azurecr.io/git-classroom:9.4.10-alpine
        ports:
        - containerPort: 6380
      imagePullSecrets:
      - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 6380
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: classroomregistry.azurecr.io/git-classroom:3.2.4-alpine
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 8888
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: classroomregistry.azurecr.io/git-classroom:1.4.26-alpine
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
  - port: 7000
  selector:
    app: memcached

